name: rankor
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.10
  - pip

  - numpy
  - pandas
  - scikit-learn
  - scipy

  - pytorch

  - scanpy
  - anndata

  - rdkit
  - openpyxl

  - matplotlib
  - seaborn
  - plotly
  - umap-learn

  - pip:
      - pytorch-metric-learning
      - cmapPy

